version: '3.3'

services:
   wordpress:
     image: doodlemania/wpmulticontainer:latest 
     volumes:
      - ${WEBAPP_STORAGE_HOME}/site/wwwroot:/var/www/html
     ports:
       - "8000:80"
     restart: always
